### ISSUE TITLE
AddSentinelAddress(...) non-running instance ClosedChannelException

### ISSUE THREAD

**Issue by oleg-gr** [mrniko/redisson#262]
Hi,

I have noticed something running some load tests recently.

I have a 3 sentinels, 1 slave and 1 master set up.

Initially I was running load tests on this exact set up and would occasionally run into `org.redisson.client.RedisConnectionException: Slave connection pool gets exhausted!` which is fine since when the load is reduced the app goes back to normal.

Then I had to switch off one of the sentinels and forgot to restart it, so now I was running with 2 sentinels, 1 slave and 1 master.

I would first again run into `org.redisson.client.RedisConnectionException: Slave connection pool gets exhausted!` but would also run into
`org.redisson.client.WriteRedisConnectionException: Can't send command: RedisCommand [name=GET, subName=null], params: [Ljava.lang.Object;@44d02cc5, channel: [id: 0x08bfe466, 0.0.0.0/0.0.0.0:55173 :> /127.0.0.1:6379]` (6379 is master)
`org.redisson.client.WriteRedisConnectionException: Can't send command: RedisCommand [name=GET, subName=null], params: [Ljava.lang.Object;@1283c11d, channel: [id: 0x05e26dda, 0.0.0.0/0.0.0.0:54360 :> /127.0.0.1:6380]` (6380 is slave)
and
`org.redisson.client.WriteRedisConnectionException: Can't send command: RedisCommand [name=GET, subName=null], params: [Ljava.lang.Object;@2f0f4c9c, channel: [id: 0xf38de559, 0.0.0.0/0.0.0.0:55367]`

here is one of them with full stack:
```
org.redisson.client.WriteRedisConnectionException: Can't send command: RedisCommand [name=GET, subName=null], params: [Ljava.lang.Object;@2f0f4c9c, channel: [id: 0xf38de559, 0.0.0.0/0.0.0.0:55367]
	at org.redisson.CommandExecutorService$6.operationComplete(CommandExecutorService.java:447)
	at org.redisson.CommandExecutorService$6.operationComplete(CommandExecutorService.java:442)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:680)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:567)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:424)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:801)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:699)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1122)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:633)
	at io.netty.channel.AbstractChannelHandlerContext.access$1900(AbstractChannelHandlerContext.java:32)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:908)
	at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:960)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:893)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:356)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:110)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.channels.ClosedChannelException: null
```

After reducing the load, `org.redisson.client.RedisConnectionException: Slave connection pool gets exhausted!` disappear, but `org.redisson.client.WriteRedisConnectionException: Can't send command...` persist and appear on every couple of calls even for 0.5QPS.

I tried this several times and it always was like this, 3 sentinels - all good, 2 sentinels - WriteRedisConnectionException exceptions.

**Note that in both cases I passed all 3 sentinel's addresses to addSentinelAddress(...) for useSentinelConnection()**

Maybe a check on the `new Redis(...)` call to ping all the sentinels would be nice

**Comment by oleg-gr** [comment]
Also reproduced the same with passing 4 sentinels to `addSentinelAddress(...)`. Works fine when all sentinels are up; throws the exceptions when one of the 4 is down before the program starts.

**Comment by mrniko** [comment]
lib version?

**Comment by oleg-gr** [comment]
2.1.3

**Comment by oleg-gr** [comment]
Looks like my judgement was wrong. It occurs even with all sentinel addresses present.

Now the errors are triggered by
```
org.redisson.client.RedisTimeoutException: null
	at org.redisson.CommandExecutorService.async(CommandExecutorService.java:439)
	at org.redisson.CommandExecutorService$5.run(CommandExecutorService.java:421)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:581)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:655)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:367)
	at java.lang.Thread.run(Thread.java:745)
```

Then it goes

```
org.redisson.client.WriteRedisConnectionException: Can't send command: RedisCommand [name=GET, subName=null], params: [Ljava.lang.Object;@c331faa, channel: [id: 0x84368eea, 0.0.0.0/0.0.0.0:62063 :> /127.0.0.1:6379]
	at org.redisson.CommandExecutorService$6.operationComplete(CommandExecutorService.java:447)
	at org.redisson.CommandExecutorService$6.operationComplete(CommandExecutorService.java:442)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:680)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:603)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:563)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:424)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:801)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:699)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1122)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:633)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:691)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:626)
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:633)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:691)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:626)
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:633)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:691)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:626)
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
	at org.redisson.client.handler.CommandsQueue.write(CommandsQueue.java:56)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:633)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:691)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:681)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:949)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:249)
	at org.redisson.client.handler.CommandsQueue.sendData(CommandsQueue.java:88)
	at org.redisson.client.handler.CommandsQueue.write(CommandsQueue.java:59)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:633)
	at io.netty.channel.AbstractChannelHandlerContext.access$1900(AbstractChannelHandlerContext.java:32)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:908)
	at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:960)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:893)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:356)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:110)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.channels.ClosedChannelException: null
```
and
```
org.redisson.client.WriteRedisConnectionException: Can't send command: RedisCommand [name=GET, subName=null], params: [Ljava.lang.Object;@447f3f6, channel: [id: 0x59f6cbcb, 0.0.0.0/0.0.0.0:62047]
	at org.redisson.CommandExecutorService$6.operationComplete(CommandExecutorService.java:447)
	at org.redisson.CommandExecutorService$6.operationComplete(CommandExecutorService.java:442)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:680)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:567)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:424)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:801)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:699)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1122)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:633)
	at io.netty.channel.AbstractChannelHandlerContext.access$1900(AbstractChannelHandlerContext.java:32)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:908)
	at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:960)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:893)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:356)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:110)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.channels.ClosedChannelException: null
```
and just continues to throw those 3 exceptions. 

If the load is reduced then only this one is occasionally appears:
```
org.redisson.client.WriteRedisConnectionException: Can't send command: RedisCommand [name=GET, subName=null], params: [Ljava.lang.Object;@299de41d, channel: [id: 0x8ff9cbb4, 0.0.0.0/0.0.0.0:62060 :> /127.0.0.1:6379]
	at org.redisson.CommandExecutorService$6.operationComplete(CommandExecutorService.java:447)
	at org.redisson.CommandExecutorService$6.operationComplete(CommandExecutorService.java:442)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:680)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:567)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:424)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:801)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:699)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1122)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:633)
	at io.netty.channel.AbstractChannelHandlerContext.access$1900(AbstractChannelHandlerContext.java:32)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:908)
	at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:960)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:893)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:356)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:110)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.channels.ClosedChannelException: null
```

**Comment by oleg-gr** [comment]
Also, the are indeed no connections with the ports that are in the errors, and one port can appear way more than "refreshConnectionAfterFails" times, so they are not being in any way cleaned up/removed from the pool/etc.

To reproduce try high loads (700QPS +)

**Comment by mrniko** [comment]
but if you getting `java.nio.channels.ClosedChannelException` then it's definitely a problem with network

**Comment by oleg-gr** [comment]
Problems with local network?

**Comment by mrniko** [comment]
i have tested Redisson in cluster mode locally and achive ~7000QPS without ClosedChannelException errors

**Comment by oleg-gr** [comment]
It's Redis 2.8
Cluster is 3.0+

**Comment by oleg-gr** [comment]
Also, even if it is indeed a network problem, I think redisson should remove the connection from its pool after several retries (isn't refreshConnectionAfterFails responsible for that?) and not through the error for the same connection forever

**Comment by oleg-gr** [comment]
Ping

**Comment by mrniko** [comment]
@oleg-gr I'll check it on this week. Little busy those days

**Comment by oleg-gr** [comment]
@mrniko ok, thank you very much :+1:

**Comment by emosemanaol** [comment]
I am seeing the same thing, I'm using version 2.1.3, and have an application that uses about 190 connections to redis, concurrently.  The timeout exception is thrown, and then I get a lot the following:

```java
class org.redisson.client.WriteRedisConnectionException-Can't send command: RedisCommand [name=EVAL, subName=null], params: [Ljava.lang.Object;@467b1786, channel: [id: 0x9f31e5db, 0.0.0.0/0.0.0.0:64587]
org.redisson.CommandExecutorService$6.operationComplete(CommandExecutorService.java:447)
org.redisson.CommandExecutorService$6.operationComplete(CommandExecutorService.java:442)
io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:680)
io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:567)
io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:424)
io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:801)
io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:699)
io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1122)
io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:633)
io.netty.channel.AbstractChannelHandlerContext.access$1900(AbstractChannelHandlerContext.java:32)
io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:908)
io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:960)
io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:893)
io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:356)
io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:110)
io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
java.lang.Thread.run(Thread.java:745)
```

I'm currently trying with the following settings:

```properties
connection.timeout=5000
retry.count=1
reconnect.delay=1000
connection.pool.size=200
```
Are there any additional tuning parameters for netty that can be tweaked that might make a difference?

**Comment by emosemanaol** [comment]
Any ideas?

My redis servers are in a sentinel configuration, with requirepass set.  I'm seeing a lot of references to the org.redisson.connection.ConnectionEntry.prepareConnection call in stack traces.  Could the sentinel configuration and/or auth being set cause deadlocks?

I'm also seeing this exception:
```java
10:58:33.711-nioEventLoopGroup-2-5-WARN i.n.u.c.SingleThreadEventExecutor:151 - A task raised an exception.
io.netty.util.concurrent.BlockingOperationException: DefaultPromise@236e14f8(incomplete)
	at io.netty.util.concurrent.DefaultPromise.checkDeadLock(DefaultPromise.java:390) ~[netty-common-4.0.30.Final.jar:4.0.30.Final]
...
```

It appears that I've got a deadlock somewhere... I've got a lot of threads all making calls on the same Redisson object, perhaps that is the issue?  I've tried isolating the Redisson object in ThreadLocal container but the resource overhead is too much.

Thanks for any insights.

**Comment by mrniko** [comment]
Sorry for so long silence. Tomorrow i'm gonna work on this issue

**Comment by emosemanaol** [comment]
I've found the problem for my application, I won't try to hijack this issue though, I'll create a new one.

**Comment by mrniko** [comment]
> It appears that I've got a deadlock somewhere

**Comment by mrniko** [comment]
@oleg-gr here is my benchmark results for 3 sentinels (one is down during test start). 1 master + 2 slaves.

Queued all 2 000 000 produce UID requests.

Memory Status: [Used: 105 MB (2% of max),  Free: 140 MB (3% of max),  Total: 245 MB (6% of max),  Max: 3 614 MB]
     1% complete.        10 429 of 2 000 000 attempted.  2 399 per sec.         0,1 min elapsed.        13,9 min remaining(est).             0 errors.
    16% complete.       320 744 of 2 000 000 attempted. 16 578 per sec.         0,3 min elapsed.         1,7 min remaining(est).             0 errors.
    32% complete.       637 551 of 2 000 000 attempted. 18 562 per sec.         0,6 min elapsed.         1,2 min remaining(est).             0 errors.
    48% complete.       954 514 of 2 000 000 attempted. 19 343 per sec.         0,8 min elapsed.         0,9 min remaining(est).             0 errors.
Memory Status: [Used: 624 MB (17% of max),  Free: 836 MB (23% of max),  Total: 1 460 MB (40% of max),  Max: 3 614 MB]
    64% complete.     1 272 660 of 2 000 000 attempted. 19 777 per sec.         1,1 min elapsed.         0,6 min remaining(est).             0 errors.
    79% complete.     1 588 905 of 2 000 000 attempted. 20 024 per sec.         1,3 min elapsed.         0,3 min remaining(est).             0 errors.
    95% complete.     1 908 263 of 2 000 000 attempted. 20 225 per sec.         1,6 min elapsed.         0,1 min remaining(est).             0 errors.
   100% complete.     2 000 000 of 2 000 000 attempted. 20 279 per sec.         1,6 min elapsed.         0,0 min remaining(est).             0 errors.

**Comment by mrniko** [comment]
@oleg-gr 
~20000QPS

**Comment by mrniko** [comment]
@oleg-gr Anyway i will add handling for this errors with channels. Slave server should be frozen for a while after few attempts. `refreshConnectionAfterFails` closes existent connection and creates a new one.

**Comment by mrniko** [comment]
Also i could add PING command for each new discovered slave to check the connection with it.

**Comment by oleg-gr** [comment]
Thank you. Let me test it in the next couple days and I will let you know

**Comment by mrniko** [comment]
@oleg-gr I think i found the way to fix this issue. I think to implement it before the this week end. Please wait

**Comment by emosemanaol** [comment]
@mrniko Thanks for the heads-up on https://github.com/mrniko/redisson/issues/274.  I see the deadlock occurring when I'm using BlockingQueue#poll(long,TimeUnit).  To work around the issue I'm using BlokcingQueue#poll() and a Thread.sleep.  The issue is still happening, but much less frequently.  I'm going to try the 2.14-SNAPSHOT and see if that resolves the issues.

**Comment by mrniko** [comment]
@emosemanaol ok, waiting for your response

**Comment by mrniko** [comment]
@oleg-gr done! I have added new config params `slaveFailedAttempts` and `slaveReconnectionTimeout`. These params manages by reconnection logic for slave node in case of connection failure. It should helps to resolve your issue.

**Comment by mrniko** [comment]
@oleg-gr Please be aware, I intend to deprecate `closeConnectionAfterFailAttempts` config setting.

**Comment by oleg-gr** [comment]
Ok, understood

**Comment by emosemanaol** [comment]
I've tested the 2.1.4-SNAPSHOT from the 14262bd25ea1739d2a7f3788c8fd67f38ec92182 update and I'm not seeing the issue anymore.

**Comment by mrniko** [comment]
@emosemanaol nice news!

**Comment by mrniko** [comment]
@oleg-gr 

I'm ready to release 2.1.4 version, just waiting for your confirmation about this issue status. Is it works now?

**Comment by oleg-gr** [comment]
Sorry, was preoccupied by other stuff. Let me try it today-tomorrow and I
will let you know. Thank you

**Comment by oleg-gr** [comment]
Are you deprecating `refreshConnectionAfterFails` config setting? Or is it the one you mean by `closeConnectionAfterFailAttempts`?

**Comment by oleg-gr** [comment]
Hm, did you change which jetty you are using, or something like that? I get 
```
Caused by: java.lang.NoClassDefFoundError: io/netty/util/internal/PlatformDependent
	at org.redisson.connection.BaseLoadBalancer.<init>(BaseLoadBalancer.java:43)
	at org.redisson.connection.RoundRobinLoadBalancer.<init>(RoundRobinLoadBalancer.java:21)
	at org.redisson.BaseMasterSlaveServersConfig.<init>(BaseMasterSlaveServersConfig.java:26)
	at org.redisson.SentinelServersConfig.<init>(SentinelServersConfig.java:31)
	at org.redisson.Config.useSentinelConnection(Config.java:160)
```

**Comment by mrniko** [comment]
@oleg-gr 
> Are you deprecating refreshConnectionAfterFails config setting? Or is it the one you mean by closeConnectionAfterFailAttempts? 

Yes, this setting is deprecated now. 

> Edit: looks like you did in 74283ca. Any idea?

It's strange why jetty can't find this class. Because `PlatformDependent` class is located in `netty-common` and i didn't remove this lib from dependency list. Anyway i returned two libs removed in previous commit. Try again

**Comment by oleg-gr** [comment]
@mrniko still getting the same error
```
Caused by: java.lang.NoClassDefFoundError: io/netty/util/internal/PlatformDependent
	at org.redisson.connection.BaseLoadBalancer.<init>(BaseLoadBalancer.java:43)
	at org.redisson.connection.RoundRobinLoadBalancer.<init>(RoundRobinLoadBalancer.java:21)
	at org.redisson.BaseMasterSlaveServersConfig.<init>(BaseMasterSlaveServersConfig.java:26)
	at org.redisson.SentinelServersConfig.<init>(SentinelServersConfig.java:31)
	at org.redisson.Config.useSentinelConnection(Config.java:160)
```
Not sure why. Investigating now

**Comment by oleg-gr** [comment]
The issue is with Jetty's version 4.0.33.Final. I changed it back to 4.0.32.Final without changing any other code and now it works.... Not sure what changes in 4.0.33.Final could have introduce this error.

**Comment by mrniko** [comment]
@oleg-gr It seems like a netty bug. I changed version to previous.

**Comment by oleg-gr** [comment]
So I got back to testing it. Right off the bat I noticed that for some reason I get no connections on master:
![screen shot 2015-11-16 at 13 54 12](https://cloud.githubusercontent.com/assets/3584701/11174644/8d4a8db2-8c6a-11e5-86f4-e26c956d0ae3.png)
It's strange, since this same set up used to produce more connections on master, than slave...

I configured the app to be hit at around 500QPS, and stop after it starts encountering errors.

For around 2-3 minutes it was holding up fine (6 connections on master, 37 on slave), but then out of the blue this occurred:
![screen shot 2015-11-16 at 13 56 09](https://cloud.githubusercontent.com/assets/3584701/11174668/d023b802-8c6a-11e5-8450-a8827e0717d4.png)

![screen shot 2015-11-16 at 13 56 20](https://cloud.githubusercontent.com/assets/3584701/11174669/d31645e8-8c6a-11e5-9f80-6ed504a0cb60.png)

The errors I got:
```
2015-11-16 13:55:36,483  WARN [http-bio-8088-exec-15]  - {get cache error - 
org.redisson.client.RedisTimeoutException: null
	at org.redisson.CommandExecutorService.async(CommandExecutorService.java:441) ~[redisson-2.1.4-SNAPSHOT.jar:na]
	at org.redisson.CommandExecutorService$5.run(CommandExecutorService.java:437) ~[redisson-2.1.4-SNAPSHOT.jar:na]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:581) ~[netty-common-4.0.32.Final.jar:4.0.32.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:655) ~[netty-common-4.0.32.Final.jar:4.0.32.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:367) ~[netty-common-4.0.32.Final.jar:4.0.32.Final]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.7.0_79]
2015-11-16 13:55:36,483  WARN [http-bio-8088-exec-40]  - {get cache error - 
org.redisson.client.RedisTimeoutException: null
	at org.redisson.CommandExecutorService.async(CommandExecutorService.java:441) ~[redisson-2.1.4-SNAPSHOT.jar:na]
	at org.redisson.CommandExecutorService$5.run(CommandExecutorService.java:437) ~[redisson-2.1.4-SNAPSHOT.jar:na]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:581) ~[netty-common-4.0.32.Final.jar:4.0.32.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:655) ~[netty-common-4.0.32.Final.jar:4.0.32.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:367) ~[netty-common-4.0.32.Final.jar:4.0.32.Final]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.7.0_79]
2015-11-16 13:55:36,483  WARN [http-bio-8088-exec-9]  - {get cache error - 
org.redisson.client.RedisTimeoutException: null
	at org.redisson.CommandExecutorService.async(CommandExecutorService.java:441) ~[redisson-2.1.4-SNAPSHOT.jar:na]
	at org.redisson.CommandExecutorService$5.run(CommandExecutorService.java:437) ~[redisson-2.1.4-SNAPSHOT.jar:na]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:581) ~[netty-common-4.0.32.Final.jar:4.0.32.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:655) ~[netty-common-4.0.32.Final.jar:4.0.32.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:367) ~[netty-common-4.0.32.Final.jar:4.0.32.Final]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.7.0_79]
2015-11-16 13:55:36,483  WARN [http-bio-8088-exec-46]  - {get cache error - 
org.redisson.client.RedisTimeoutException: null
	at org.redisson.CommandExecutorService.async(CommandExecutorService.java:441) ~[redisson-2.1.4-SNAPSHOT.jar:na]
	at org.redisson.CommandExecutorService$5.run(CommandExecutorService.java:437) ~[redisson-2.1.4-SNAPSHOT.jar:na]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:581) ~[netty-common-4.0.32.Final.jar:4.0.32.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:655) ~[netty-common-4.0.32.Final.jar:4.0.32.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:367) ~[netty-common-4.0.32.Final.jar:4.0.32.Final]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.7.0_79]
2015-11-16 13:55:36,483  WARN [http-bio-8088-exec-7]  - {get cache error - 
org.redisson.client.RedisTimeoutException: null
	at org.redisson.CommandExecutorService.async(CommandExecutorService.java:441) ~[redisson-2.1.4-SNAPSHOT.jar:na]
	at org.redisson.CommandExecutorService$5.run(CommandExecutorService.java:437) ~[redisson-2.1.4-SNAPSHOT.jar:na]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:581) ~[netty-common-4.0.32.Final.jar:4.0.32.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:655) ~[netty-common-4.0.32.Final.jar:4.0.32.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:367) ~[netty-common-4.0.32.Final.jar:4.0.32.Final]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.7.0_79]
2015-11-16 13:55:36,483  WARN [http-bio-8088-exec-19]  - {get cache error - 
org.redisson.client.RedisTimeoutException: null
	at org.redisson.CommandExecutorService.async(CommandExecutorService.java:441) ~[redisson-2.1.4-SNAPSHOT.jar:na]
	at org.redisson.CommandExecutorService$5.run(CommandExecutorService.java:437) ~[redisson-2.1.4-SNAPSHOT.jar:na]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:581) ~[netty-common-4.0.32.Final.jar:4.0.32.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:655) ~[netty-common-4.0.32.Final.jar:4.0.32.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:367) ~[netty-common-4.0.32.Final.jar:4.0.32.Final]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.7.0_79]
2015-11-16 13:55:36,484 ERROR [http-bio-8088-exec-15]  - FAILED TO GET FROM CACHE - 
2015-11-16 13:55:36,484  WARN [http-bio-8088-exec-74]  - {get cache error - 
org.redisson.client.RedisTimeoutException: null
	at org.redisson.CommandExecutorService.async(CommandExecutorService.java:441) ~[redisson-2.1.4-SNAPSHOT.jar:na]
	at org.redisson.CommandExecutorService$5.run(CommandExecutorService.java:437) ~[redisson-2.1.4-SNAPSHOT.jar:na]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:581) ~[netty-common-4.0.32.Final.jar:4.0.32.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:655) ~[netty-common-4.0.32.Final.jar:4.0.32.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:367) ~[netty-common-4.0.32.Final.jar:4.0.32.Final]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.7.0_79]
2015-11-16 13:55:36,484  WARN [http-bio-8088-exec-26]  - {get cache error - 
org.redisson.client.RedisTimeoutException: null
	at org.redisson.CommandExecutorService.async(CommandExecutorService.java:441) ~[redisson-2.1.4-SNAPSHOT.jar:na]
	at org.redisson.CommandExecutorService$5.run(CommandExecutorService.java:437) ~[redisson-2.1.4-SNAPSHOT.jar:na]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:581) ~[netty-common-4.0.32.Final.jar:4.0.32.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:655) ~[netty-common-4.0.32.Final.jar:4.0.32.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:367) ~[netty-common-4.0.32.Final.jar:4.0.32.Final]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.7.0_79]
2015-11-16 13:55:36,484  WARN [http-bio-8088-exec-2]  - {get cache error - 
org.redisson.client.RedisTimeoutException: null
	at org.redisson.CommandExecutorService.async(CommandExecutorService.java:441) ~[redisson-2.1.4-SNAPSHOT.jar:na]
	at org.redisson.CommandExecutorService$5.run(CommandExecutorService.java:437) ~[redisson-2.1.4-SNAPSHOT.jar:na]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:581) ~[netty-common-4.0.32.Final.jar:4.0.32.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:655) ~[netty-common-4.0.32.Final.jar:4.0.32.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:367) ~[netty-common-4.0.32.Final.jar:4.0.32.Final]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.7.0_79]
2015-11-16 13:55:36,487 ERROR [http-bio-8088-exec-40]  - FAILED TO GET FROM CACHE - 
2015-11-16 13:55:36,487  WARN [http-bio-8088-exec-25]  - {get cache error - 
org.redisson.client.RedisTimeoutException: null
	at org.redisson.CommandExecutorService.async(CommandExecutorService.java:441) ~[redisson-2.1.4-SNAPSHOT.jar:na]
	at org.redisson.CommandExecutorService$5.run(CommandExecutorService.java:437) ~[redisson-2.1.4-SNAPSHOT.jar:na]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:581) ~[netty-common-4.0.32.Final.jar:4.0.32.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:655) ~[netty-common-4.0.32.Final.jar:4.0.32.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:367) ~[netty-common-4.0.32.Final.jar:4.0.32.Final]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.7.0_79]
2015-11-16 13:55:36,490  WARN [http-bio-8088-exec-31]  - {get cache error - 
org.redisson.client.RedisTimeoutException: null
	at org.redisson.CommandExecutorService.async(CommandExecutorService.java:441) ~[redisson-2.1.4-SNAPSHOT.jar:na]
	at org.redisson.CommandExecutorService$5.run(CommandExecutorService.java:437) ~[redisson-2.1.4-SNAPSHOT.jar:na]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:581) ~[netty-common-4.0.32.Final.jar:4.0.32.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:655) ~[netty-common-4.0.32.Final.jar:4.0.32.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:367) ~[netty-common-4.0.32.Final.jar:4.0.32.Final]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.7.0_79]
2015-11-16 13:55:36,490  WARN [http-bio-8088-exec-29]  - {get cache error - 
org.redisson.client.RedisTimeoutException: null
	at org.redisson.CommandExecutorService.async(CommandExecutorService.java:441) ~[redisson-2.1.4-SNAPSHOT.jar:na]
	at org.redisson.CommandExecutorService$5.run(CommandExecutorService.java:437) ~[redisson-2.1.4-SNAPSHOT.jar:na]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:581) ~[netty-common-4.0.32.Final.jar:4.0.32.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:655) ~[netty-common-4.0.32.Final.jar:4.0.32.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:367) ~[netty-common-4.0.32.Final.jar:4.0.32.Final]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.7.0_79]
2015-11-16 13:55:36,490  WARN [http-bio-8088-exec-66]  - {get cache error - 
org.redisson.client.RedisTimeoutException: null
	at org.redisson.CommandExecutorService.async(CommandExecutorService.java:441) ~[redisson-2.1.4-SNAPSHOT.jar:na]
	at org.redisson.CommandExecutorService$5.run(CommandExecutorService.java:437) ~[redisson-2.1.4-SNAPSHOT.jar:na]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:581) ~[netty-common-4.0.32.Final.jar:4.0.32.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:655) ~[netty-common-4.0.32.Final.jar:4.0.32.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:367) ~[netty-common-4.0.32.Final.jar:4.0.32.Final]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.7.0_79]
2015-11-16 13:55:36,490  WARN [http-bio-8088-exec-28]  - {get cache error - 
org.redisson.client.RedisTimeoutException: null
	at org.redisson.CommandExecutorService.async(CommandExecutorService.java:441) ~[redisson-2.1.4-SNAPSHOT.jar:na]
	at org.redisson.CommandExecutorService$5.run(CommandExecutorService.java:437) ~[redisson-2.1.4-SNAPSHOT.jar:na]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:581) ~[netty-common-4.0.32.Final.jar:4.0.32.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:655) ~[netty-common-4.0.32.Final.jar:4.0.32.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:367) ~[netty-common-4.0.32.Final.jar:4.0.32.Final]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.7.0_79]
2015-11-16 13:55:36,493  WARN [http-bio-8088-exec-73]  - {get cache error - 
org.redisson.client.RedisTimeoutException: null
	at org.redisson.CommandExecutorService.async(CommandExecutorService.java:441) ~[redisson-2.1.4-SNAPSHOT.jar:na]
	at org.redisson.CommandExecutorService$5.run(CommandExecutorService.java:437) ~[redisson-2.1.4-SNAPSHOT.jar:na]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:581) ~[netty-common-4.0.32.Final.jar:4.0.32.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:655) ~[netty-common-4.0.32.Final.jar:4.0.32.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:367) ~[netty-common-4.0.32.Final.jar:4.0.32.Final]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.7.0_79]
```

From previous trials I know that if I stop hitting the app with 500QPS, and just start doing 1QPS, I will still get the same error for every single call until I restart the app.

I'll keep investigating, but help would be appreciated.

The config that I use:
```
"sentinels": [
        "127.0.0.1:26379",
        "127.0.0.1:26380",
        "127.0.0.1:26381"
      ],
"masterName": "test-redis-api",
"password": "test-redis-api",
"timeout": 100,
"masterConnectionPoolSize": 20,
"slaveConnectionPoolSize": 30,
"retryAttempts": 3,
"retryInterval": 100,
"clientName": "local-redis-test",
"slaveFailedAttempts": 3,
"slaveReconnectionTimeout": 100,
"database": 3
```

**Comment by oleg-gr** [comment]
Basically, it looks to me like redisson opens the maximum allowed number of connections (e.g. in the above case, the slave has 7 connections initially (including sentinels, cli, etc.), and then redisson opens 30 more, since slaveConnectionPoolSize is 30). After running for some time in this configuration Redisson tries to open more connections and everything blows up...

**Comment by mrniko** [comment]
Could you share your test code? it would be helpful for me.

**Comment by oleg-gr** [comment]
It's literally just Jersey Spring servlet app with the following code for getting from cache
```
    public Object get(Object key) {
        RBucket bucket = redisson.getBucket((String) key, serializationCodec);
        Object result = bucket.get();
        return result;
    }
```
And redisson is created with `Redisson.create(config)`, where config is created from the values I posted above.

I can't share the exact code since there is a lot of environment to set up to run it locally. How about I will try to recreate the same scenario with a simple app and see if it happens again? I don't personally think the problem is with the app, since the logic is simple enough that it should not cause problems.

**Comment by mrniko** [comment]
I have master + 2 slave nodes. Then one slave node is down and up few minutes later I see infinity reconnection in slave node logs.

**Comment by mrniko** [comment]
@oleg-gr 
Your use case looks quite simple. I don't ever think that the problem is in your app. Just wanted look at Redisson code usage. I have make few improvements. Please try to run your app again.

**Comment by mrniko** [comment]
@oleg-gr Additional improvements

**Comment by oleg-gr** [comment]
> I have master + 2 slave nodes. Then one slave node is down and up few minutes later I see infinity reconnection in slave node logs.
Does this mean you were able to reproduce it?

let me test the app again.

**Comment by oleg-gr** [comment]
Hm, still the same behaviour:
```
2015-11-17 10:36:40,987  WARN [http-bio-8088-exec-53] - {get cache error -
org.redisson.client.RedisTimeoutException: Command execution timeout for command: (GET) with params [KEY_506a8f90-b93d-11e1-b366-005056bd6847]
	at org.redisson.CommandExecutorService.async(CommandExecutorService.java:444) ~[redisson-2.1.5-SNAPSHOT.jar:na]
	at org.redisson.CommandExecutorService$5.run(CommandExecutorService.java:440) ~[redisson-2.1.5-SNAPSHOT.jar:na]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:581) ~[netty-common-4.0.32.Final.jar:4.0.32.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:655) ~[netty-common-4.0.32.Final.jar:4.0.32.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:367) ~[netty-common-4.0.32.Final.jar:4.0.32.Final]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.7.0_79]
```
My setup is 1 master and 1 slave. I do not get any connections to master for some reason. Only to slave.

When you reproduced the problem were you able to fix it with the improvements you committed?

**Comment by oleg-gr** [comment]
By the way, using 2.1.3, I get connections to both master and slave with the same config and same set up

**Comment by oleg-gr** [comment]
Actually, in 2.1.3 after getting timeouts, after that I can still use the app without restart and connections won't time out all the time. In 2.1.5-SNAPSHOT, if I get timeouts, I will get them on every call until I restart the app... I am not sure which change introduced it.

Hm, what do you think?..

**Comment by mrniko** [comment]
> Does this mean you were able to reproduce it?

I tried to reproduce slave-down behavior. With 2 sentinels, 1 master and 2 slaves. The connection is always perfect. So I had shutdown slave server but i got infinity reconnection to alive slave server when it has come back. It was a bug and it was fixed.

I use windows 7 for testing. Would you try to replace netty 4.0.32 to 4.0.30 as in 2.1.3 version. Maybe this helps.

**Comment by oleg-gr** [comment]
@mrniko I see. I get this without putting any of the slaves down. I will try with netty 4.0.30
I use Mac for testing if that matters

**Comment by oleg-gr** [comment]
@mrniko same problem: no connections to master; timeouts and not being able to recover from them... Basically, currently I observe the best behaviour in 2.1.3:
It starts timing out, and will through timeouts indefinitely until the QPS doesn't drop (I guess it doesn't have enough time to run some internal logic), but after QPS drops and you make calls at lower QPS, there are no timeouts. With 2.1.5-SNAPSHOT, once you get timeouts, you will always get timeouts. It's also worse since in 2.1.5-SNAPSHOT redisson doesn't create connections to master for some reason...

**Comment by oleg-gr** [comment]
Same applies for 2.1.4, so something changed between 2.1.3 and 2.1.4 that introduced this weird behaviour

**Comment by mrniko** [comment]
You are right, the connection acquiring algorithm has changed in 2.1.4 not it's fully async rather than sync link in previous Redisson versions. I fixed a bug in connectAsync method.

**Comment by oleg-gr** [comment]
Having the same issues. More side affects now:
1) still no connections to master are being opened; in the beginning, 5 connections were opened, but stayed idle for the rest of the time
2) got a connection leak on slave; sometimes redisson would open new connections, but it seems like the old ones are either not released properly or the slave pool size setting is not being respected

**Comment by mrniko** [comment]
I revised the command retry logic, now it should work more accurate with timeout.

**Comment by mrniko** [comment]
have you checked it?

**Comment by oleg-gr** [comment]
@mrniko thank you. This works better. When it times out at high loads, it is possible to recover without restarting the app. But if you keep the load high for a long period of time, than when you stop the high load and try to get from cache again, it still timeout's on each request. Another problem is I still get no connections to master, only to slave. Are you able to reproduce this problem? I can't see the problem in my application... I will try to reproduce the issue in a very very simple app and see if it still exists

**Comment by mrniko** [comment]
> But if you keep the load high for a long period of time, than when you stop the high load and try to get from cache again, it still timeout's on each request

Can't reproduce it. After short amount of time test system returned to normal state without any errors.

> Another problem is I still get no connections to master, only to slave. 

At test system startup I always have a master and two slaves with good connection.

Try to reproduce it with my "tester" https://yadi.sk/d/5nYwffqZkgycT. class to lunch is `com.firepod.tools.redisloadr.LoadR`, config definition in `LoadR.getRedisson`

**Comment by mrniko** [comment]
i made small improvement for connectionpool could you please

**Comment by oleg-gr** [comment]
Ok, now it's possible to recover after high load. Thank you for this fix. 

Now the major problem is that I am not getting any connections to master. My set up is one master and one slave. Here is the related config:
```
      "timeout": 100,
      "masterConnectionPoolSize": 10,
      "slaveConnectionPoolSize": 10,
      "retryAttempts": 3,
      "retryInterval": 100,
      "slaveFailedAttempts": 3,
      "slaveReconnectionTimeout": 100,
      "masterConnectionMinimumIdleSize": 2,
      "slaveConnectionMinimumIdleSize": 2
```
Now, when I start the app I get 2 connections opened on master and 3 on slave. When I start high load testing, I get all 10 connections open on slave, but no new connections on master. Then some of the calls start timing out, but still no new connections on master are opened. The original two connections to master are not being used either (their age is equal to idle time). After I stop high load, connections on master and on slave both drop to 1 (not 2 as per settings).

**Comment by mrniko** [comment]
> After I stop high load, connections on master and on slave both drop to 1 (not 2 as per settings).

fixed

**Comment by mrniko** [comment]
> Now the major problem is that I am not getting any connections to master

Could you send me redisson logs (you need to switch logging to 'TRACE' level)?

**Comment by oleg-gr** [comment]
Getting 2 connections to master and 3 to slave at the start (both masterConnectionMinimumIdleSize and slaveConnectionMinimumIdleSize are set to 2).

So now I started with heavy lot and small time to warm up. At some point Redisson just dies completely (stops outputting logs and all the calls are failing). In this scenario this is what the log looks like. Everything with ## is added by me since there is too much data output since the value of my key is pretty big. Master is running on 6379 and it's never being called

[testFile.txt](https://github.com/mrniko/redisson/files/44551/testFile.txt)

**Comment by mrniko** [comment]
> Master is running on 6379 and it's never being called

**Comment by mrniko** [comment]
> Everything with ## is added by me since there is too much data output since the value of my key is pretty big.

**Comment by oleg-gr** [comment]
@mrniko calls to 6379 are only the initial ones (opening first 3 connections), after that all the calls are done to 6380.

Also, what do you mean which redisson object? I initialise one and keep using

**Comment by mrniko** [comment]
> what do you mean which redisson object

Sorry, I mean object type RMap, RTopic... etc. And that about the message size that is it?

**Comment by mrniko** [comment]
@oleg-gr ?

**Comment by oleg-gr** [comment]
@mrniko Sorry, was preoccupied. 

1) The object used is RBucket. I removed message because it's just too much output at 200QPS to output to logs.

2) Previously, redisson used to read from both slave and master, so I was confused why it now reads only from slave. The correct behaviour is to read only from slave, so it's correct as it is now.

3) I tried the 2.2.0 branch and it seemed to work much better. Do you know when you are going to release it?

**Comment by mrniko** [comment]
2.2.0 released today! Grab it while it hot :)

**Comment by oleg-gr** [comment]
Awesome. Quick suggestion, can you set `void setSentinelServersConfig(SentinelServersConfig sentinelConnectionConfig)` to public in Config.java? I want to be able to just set it directly, since I am reading a json config into a `SentinelServersConfig` instance

**Comment by oleg-gr** [comment]
Actually, it would be better if you added a method like
```
public SentinelServersConfig useSentinelServers(SentinelServersConfig config)
```

**Comment by oleg-gr** [comment]
Otherwise, that's what I have to do
```
SentinelServersConfig redissonConfig = getJsonConfig(SentinelServersConfig.class);

Config config = new Config();
SentinelServersConfig sentinelServersConfig = config.useSentinelServers();
for (java.net.URI address : redissonConfig.getSentinelAddresses()) {
       sentinelServersConfig.addSentinelAddress(address.toString());
}
sentinelServersConfig.setMasterName(redissonConfig.getMasterName());
sentinelServersConfig.setClientName(redissonConfig.getClientName());
sentinelServersConfig.setDatabase(redissonConfig.getDatabase());
sentinelServersConfig.setMasterConnectionPoolSize(redissonConfig.getMasterConnectionPoolSize());
sentinelServersConfig.setPassword(StringEncrypter.decrypt(redissonConfig.getPassword()));
sentinelServersConfig.setRetryAttempts(redissonConfig.getRetryAttempts());
sentinelServersConfig.setRetryInterval(redissonConfig.getRetryInterval());
sentinelServersConfig.setSlaveConnectionPoolSize(redissonConfig.getSlaveConnectionPoolSize());
sentinelServersConfig.setTimeout(redissonConfig.getTimeout());
```

**Comment by mrniko** [comment]
@oleg-gr i have just added useSentinelServers with config param.

**Comment by oleg-gr** [comment]
@mrniko Sounds great. And thanks for all the bugfixes and putting so much time into open source. Спасибо :-)
