### ISSUE TITLE
RMapCache.values() fails

### ISSUE THREAD

**Issue by neilwightman** [mrniko/redisson#471]
I recently change some code to use maxIdle timeouts on a map.  I.e changed from RMap to RMapCache.   Put and gets are working as expected but the .values() call doesnt work.

ERR Error running script (call to f_7e9dc69eeb0d7798de8f6a1bb0f5a10381585c62): @user_script:1: @user_script: 1: Write commands not allowed after non deterministic commands . channel: [id: 0x52db1332, L:/127.0.0.1:37320 - R:localhost/127.0.0.1:6379] command: CommandData [promise=ImmediateEventExecutor$ImmediatePromise@5ba21282(incomplete), command=(EVAL), params=[local result = {}; local res = redis.call('hscan', KEYS[1], ARGV[2]); for i, value in ipairs(res[2]) do if i % 2 == 0 then local key = res[2][i-1]; local expireDate = 92233720368547758; local expireDateScore = redis.call('zscore', KEYS[2], key); if expireDateScore ~= false then expireDate = tonumber(expireDateScore) end; local t, val = struct.unpack('dLc0', value); if t ~= 0 then local expireIdle = redis.call('zscore', KEYS[3], key); if expireIdle ~= false then if tonumber(expireIdle) > tonumber(ARGV[1]) then local value = struct.pack('dLc0', t, string.len(val), val); redis.call('hset', KEYS[1], key, value); redis.call('zadd', KEYS[3], t + tonumber(ARGV[1]), key); end; expireDate = math.min(expireDate, tonumber(expireIdle)) end; end; if expireDate > tonumber(ARGV[1]) then table.insert(result, key); table.insert(result, val); end; end; end;return {res[1], result};, 3, testRMapCacheValues, redisson__timeout__set__{testRMapCacheValues}, redisson__idle__set__{testRMapCacheValues}, 1460720927535, 0], codec=org.redisson.client.codec.ScanCodec@6d6d43cd]

I have attached a test class to show this.

**Comment by neilwightman** [comment]
[RMapCacheTest.txt](https://github.com/mrniko/redisson/files/220997/RMapCacheTest.txt)

**Comment by neilwightman** [comment]
map.readAllValues() also doesnt work.

**Comment by jackygurui** [comment]
What version of redisson is this test for?

**Comment by neilwightman** [comment]
Redisson 2.2.11
Redis 3.0.7 - Release date: 25 jan 2016

**Comment by jackygurui** [comment]
Does it fail on the master branch? I think they are fixed in #469 and #470 .

**Comment by neilwightman** [comment]
No sorry.  It fails with current master.   I had to fix a compilation issue where a class doesnt fully implement an interface ( org/redisson/spring/cache/RedissonCache.java ) but I just created an empty method and disabled tests.   The test class attached above still fails.

**Comment by jackygurui** [comment]
Ah, ```map.put("1234", "5678", 1, TimeUnit.MINUTES, 60, TimeUnit.MINUTES); ``` fails while ```map.put("1234", "5678", 1, TimeUnit.MINUTES); ``` passes. Looks like the problem is at the idle time side.

Looks like map.readAllValues() problem is another matter.

**Comment by mrniko** [comment]
Fixed
